### ISSUE TITLE
Constantly getting npm errors and it doesn't even start up

### ISSUE THREAD

**Issue by ShockedCoder** [cokolele/terraria-map-editor#11]
I installed it 3 different ways, with user perms, with root perms, and root only used on the npm cmds. but it still won't start up.
I did everything as it said, but it still refused to start.

My system and specs:
```
OS: Manjaro Linux x86_64
Kernel: 5.9.16-1-MANJARO
CPU: Intel i9-9900K (16) @ 5.000GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
```

**Comment by cokolele** [comment]
App bundler Parcel v1 that is used in this project is outdated. I choose not to update it to the current v2 beta since it would take a lot of effort and this version is *still* perfectly functional. You just get a bit of errors that can't be fixed by me:


> ![image](https://user-images.githubusercontent.com/26676195/107427897-2b08f700-6b22-11eb-9902-c8342f337d6f.png)

As for not even building the app, i can't possibly figure it out just by looking at your specs. My best guess is that some packages error while install building for linux.
